local openssl = require('openssl')
local print_r = require('function.print_r')
require 'l-io'

print('load openssl.cnf', string.rep('-',40))
data = io.loaddata('.\\openssl.cnf')
conf = openssl.lhash_read(data)
print(conf)
print(conf:parse(false))
print('parse openssl.cnf as table', string.rep('-',40))
print(io.hex_dump(conf:parse()))
print('parse openssl.cnf as table', string.rep('-',40))
print(conf:get_string('ca','default_ca'))
print(conf:get_string('CA_default','default_days'))
print('从表中载入配置', string.rep('-',40))
io.read('*l')
c1 = openssl.lhash_load(conf:export())
print(c1)
print(io.hex_dump(c1:parse()))
