---
-- Provide STACK_OF(object) maintance in lua.
-- STACK\_OF(CTYPE) object just like STACK\_OF(X509) are high frequency used,
-- in x509, pkcs7, pkcs12 and others module, and it has complex APIs in openssl.
-- In lua-openssl, all of STACK\_OF(CTYPE) C side objects are mapping to array
-- actually table in Lua side, and follow the rules of the Lua array, start
-- index from 1, not 0 in C world.
-- E.g C side STACK\_OF(X509) and Lua side array {cert1,cert2,...,certn} can
-- be automatic convert in lua\-openssl if need.
--
-- @module sk
--